# apiVersion: v1
# kind: Secret
# metadata:
#   name: dockerhub-secret
#   namespace: default  # Change if deploying to a different namespace
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: "" # echo -n '{"auths":{"docker.io":{"username":"<your-username>","password":"<your-password>","email":"<your-email>"}}}' | base64
