apiVersion: v1
kind: Service
metadata:
  name: finance-portal-service
  namespace: default
spec:
  selector:
    app: finance-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Or ClusterIP if using Ingress